spring.application.name=ComputerDesign

server.address=0.0.0.0
server.port=8105

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Computer_Design
spring.datasource.username=root
spring.datasource.password=123456

# ?????????????????
mybatis.configuration.map-underscore-to-camel-case=true


# QQ
spring.mail.host=smtp.qq.com
spring.mail.username=3521235763@qq.com
spring.mail.password=zxzfecdchodhdbge
spring.mail.port=587
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.debug=true

# ifly
spark.apiKey=3d73d5b03ccb0cd8834bb87797c45232
spark.apiSecret=MzgzMzMwYWMzYjZlMzhiYmM0OWQ2Njc0
spark.appid=3efb053a
spark.hostUrl=https://spark-api.xf-yun.com/v1.1/chat
spark.domain=lite

# ????????
spring.web.resources.static-locations=file:./uploads/


file.upload-dir=./uploads

# ??????
file.video-image-upload-dir=uploads/video/vedio

file.course-upload-dir=uploads/video/course
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# ????URL??
app.base-url=http://localhost:8105/

# video
Manager_Vedio_course_image=http://localhost:8105/video/course/
Manager_Vedio_video=http://localhost:8105/video/vedio/

# User
User_Avatar_Show_Url=http://localhost:8105/avatar/
User_Avatar_Upload_Dir=uploads/avatar/
User_Avatar_Default_Url=http://localhost:8105/avatar/Default.jpg

Base_Url=http://localhost:8105/
